[colors]
background=101418ff
text=bac8dbff
prompt=9fcafcff
placeholder=c2c7cfff
input=e1e2e8ff
match=9fcafcff
selection=174974ff
selection-text=d0e4ffff
selection-match=e1e2e8ff
# counter=disabled
border=9fcafcff
