[colors]
background=101417ff
text=b8c8d9ff
prompt=96ccf8ff
placeholder=c1c7ceff
input=e0e3e8ff
match=96ccf8ff
selection=004b70ff
selection-text=cae6ffff
selection-match=e0e3e8ff
# counter=disabled
border=96ccf8ff
