[config]
mode = "first"
reload_apps = true 
reload_apps_list = ["waybar"]

[config.wallpaper]
set = true
pre_hook = "pkill swaybg || true"
command = "swaybg -i {{ image }} &"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"
# post_hook = "pkill waybar || true"
post_hook = "pkill -SIGUSR2 waybar"

