[config]
mode = "first"
reload_apps = true 
reload_apps_list = ["waybar"]

[config.wallpaper]
set = true
pre_hook = "pkill swaybg || true"
command = "swaybg -i {{ image }} &"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"
# post_hook = "pkill waybar || true"
post_hook = "pkill -SIGUSR2 waybar"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.lua'
output_path = '~/.config/hypr/modules/colors.lua'

[templates.foot]
input_path = '~/.config/matugen/templates/foot.ini'
output_path = '~/.config/foot/colors.ini'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.vscode-raw]
input_path = '~/.config/matugen/templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = '~/.config/matugen/templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'


