[colors]
background={{colors.surface.default.hex_stripped}}ff
text={{colors.secondary.default.hex_stripped}}ff
prompt={{colors.primary.default.hex_stripped}}ff
placeholder={{colors.on_surface_variant.default.hex_stripped}}ff
input={{colors.inverse_surface.default.hex_stripped}}ff
match={{colors.primary.default.hex_stripped}}ff
selection={{colors.primary_container.default.hex_stripped}}ff
selection-text={{colors.on_primary_container.default.hex_stripped}}ff
selection-match={{colors.inverse_surface.default.hex_stripped}}ff
# counter=disabled
border={{colors.primary.default.hex_stripped}}ff
